revert: "chore(sync): add python build system"
This reverts commit e50316ca896c18a41b3ba70e7f73be1afb932aff.

ImportError: cannot import name 'main' from 'synchronizer' (unknown location)

https://github.com/ScottyLabs/governance/actions/runs/20835225055/job/59858465905